DELETE /api/manager/permissions/d74098f4-128f-3c11-98ce-d474fabd010e HTTP/1.1
Host: localhost
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|ru5847XzGb1iGvQ9M0VfzVUjvmMGFO5p4ztBZ3Nu2e0eee7b
